"""Spec reading and prompt-driven planning helpers."""

from __future__ import annotations

from pathlib import Path

from agent import logger
from agent.model_client import OllamaClient
from agent.prompts import IMPLEMENTATION_PLAN_PROMPT, SPEC_SUMMARY_PROMPT


def read_spec(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def summarize_spec(client: OllamaClient, spec: str) -> str:
    prompt = SPEC_SUMMARY_PROMPT.format(spec=spec)
    logger.log_prompt(prompt)
    response = client.generate(prompt)
    logger.log_decision(f"Spec summary generated by {response.model}:\n{response.text}")
    return response.text


def create_plan(client: OllamaClient, summary: str) -> str:
    prompt = IMPLEMENTATION_PLAN_PROMPT.format(summary=summary)
    logger.log_prompt(prompt)
    response = client.generate(prompt)
    logger.log_decision(f"Implementation plan generated by {response.model}:\n{response.text}")
    return response.text

