"""Spec reading and prompt-driven planning helpers."""

from __future__ import annotations

import re
from pathlib import Path

from agent import logger
from agent.model_client import OllamaClient
from agent.prompts import (
    IMPLEMENTATION_PLAN_PROMPT,
    SPEC_SUMMARY_PROMPT,
)

IMPORTANT_REQUIREMENT_KEYWORDS = [
    "must",
    "required",
    "include",
    "json",
    "field",
    "output",
    "edge case",
    "stderr",
    "stdout",
    "exit code",
    "return",
    "print",
]


def read_spec(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def extract_output_fields(spec_text: str) -> list[str]:
    fields = set()

    patterns = [
        r'"([a-zA-Z0-9_]+)"',
        r"'([a-zA-Z0-9_]+)'",
        r"\b([a-zA-Z_]+_count)\b",
        r"\b(id|name|active|status|result|error)\b",
    ]

    for pattern in patterns:
        matches = re.findall(pattern, spec_text)

        for match in matches:
            if isinstance(match, tuple):
                for item in match:
                    if item:
                        fields.add(item)
            else:
                fields.add(match)

    return sorted(fields)


def extract_requirements(spec_text: str) -> list[str]:
    requirements = []

    for line in spec_text.splitlines():
        cleaned = line.strip()

        if not cleaned:
            continue

        lowered = cleaned.lower()

        if any(
            keyword in lowered
            for keyword in IMPORTANT_REQUIREMENT_KEYWORDS
        ):
            requirements.append(cleaned)

    return sorted(set(requirements))


def build_static_analysis(spec_text: str) -> str:
    requirements = extract_requirements(spec_text)

    output_fields = extract_output_fields(spec_text)

    sections = []

    if requirements:
        sections.append("STATIC REQUIREMENTS:")

        for item in requirements:
            sections.append(f"- {item}")

    if output_fields:
        sections.append("\nDETECTED OUTPUT FIELDS:")

        for field in output_fields:
            sections.append(f"- {field}")

    return "\n".join(sections)


def summarize_spec(client: OllamaClient, spec: str) -> str:
    static_analysis = build_static_analysis(spec)

    prompt = SPEC_SUMMARY_PROMPT.format(
        spec=spec,
        static_analysis=static_analysis,
    )

    logger.log_prompt(prompt)

    response = client.generate(prompt)

    combined_summary = (
        static_analysis
        + "\n\nMODEL SUMMARY:\n"
        + response.text
    )

    logger.log_decision(
        f"Spec summary generated by {response.model}:\n"
        f"{combined_summary}"
    )

    return combined_summary


def create_plan(client: OllamaClient, summary: str) -> str:
    prompt = IMPLEMENTATION_PLAN_PROMPT.format(summary=summary)

    logger.log_prompt(prompt)

    response = client.generate(prompt)

    logger.log_decision(
        f"Implementation plan generated by {response.model}:\n"
        f"{response.text}"
    )

    return response.text